apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  namespace: default
  name: zoo1
spec:
  serviceName: "zoo1"
  podManagementPolicy: Parallel
  replicas: 1
  template:
    metadata:
      labels:
        component: zoo1
    spec:
      terminationGracePeriodSeconds: 10
      initContainers:
        - name: init-svc 
          image: centos:7 
          imagePullPolicy: IfNotPresent
          command: 
            - /bin/sh 
            - -c
            - |
              for i in $(seq -s 1 10); do
                COUNT=0
                for j in $(seq -s 1 3); do
                  [[ $(getent hosts zoo${j}) ]] && COUNT=$[${COUNT}+1]
                done
                if [[ 3 -eq ${COUNT} ]]; then
                  exit 0
                else
                  sleep 1
                fi
              done
              exit 1  
      containers:
        - name: zoo1
          image: zookeeper:3.4 
          imagePullPolicy: IfNotPresent
          env:
            - name: ZOO_MY_ID 
              value: "1"
            - name: ZOO_SERVERS 
              value: "server.1=0.0.0.0:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - containerPort: 2181 
            - containerPort: 2888
            - containerPort: 3888
          volumeMounts:
            - name: host-time
              mountPath: /etc/localtime
              readOnly: true
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
